/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.Controlador_FRM_Usuarios;
import javax.swing.table.DefaultTableModel;
import Modelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Frm_Usuarios extends javax.swing.JFrame {

    public Controlador_FRM_Usuarios controlador;
    
    private DefaultTableModel modelo;
    
    private Usuario usuario;
    /**
     * Creates new form Frm_Usuarios
     */
    public Frm_Usuarios() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        this.controlador = new Controlador_FRM_Usuarios(this);
        
        this.jP_Botones1.agregarControladorU(controlador);
        
        this.estadoInicial();
        
        this.modelo = new DefaultTableModel();
        
        String [] columnas = new String [4];
        columnas [0] = "Usuarios";
        columnas[1] = "Contraseña";
        columnas[2] = "Nombre Completo";
        columnas[3] = "Tipo";
        
        this.modelo.setColumnIdentifiers(columnas);
        
        this.jtListaPerfiles.setModel(modelo);
    }
    
    
    public void estadoInicial(){
    
    this.jtUsuario.setText("");
    this.jpContrasena.setText("");
    this.jpConfirmar.setText("");
    this.jtNombreComp.setText("");
    this.jcTipo.setSelectedIndex(0);
    
    
    this.jtUsuario.setEnabled(true);
    this.jpContrasena.setEnabled(false);
    this.jtNombreComp.setEnabled(false);
    this.jpConfirmar.setEnabled(false);
    this.jcTipo.setEnabled(false);
    
    
    this.jP_Botones1.estadoInicialBotones();
    }
    
    public Usuario obtenerUsuario(){
    
    this.usuario = new Usuario(this.jtUsuario.getText(),
    this.jpContrasena.getText(),
    this.jtNombreComp.getText(),
    this.jcTipo.getSelectedItem().toString());
    
    return this.usuario;
    }
    
    public void habilitarModificar(){
    this.jtUsuario.setEnabled(false);
    this.jpContrasena.setEnabled(true);
    this.jpConfirmar.setEnabled(true);
    this.jtNombreComp.setEnabled(true);
    this.jcTipo.setEnabled(true);
    
    this.jP_Botones1.habilitarBotoneraModificarEliminar();
    
    }
    
    public void habilitarAgregar(){
    
    this.jtUsuario.setEnabled(false);
    this.jpContrasena.setEnabled(true);
    this.jpConfirmar.setEnabled(true);
    this.jtNombreComp.setEnabled(true);
    this.jcTipo.setEnabled(true);
    
    this.jP_Botones1.habilitarBotoneraAgregar();
    }
    
    public void cargarDatosUsuario(Usuario pUsuario){
    
    this.jpContrasena.setText(pUsuario.getContrasena());
    this.jpConfirmar.setText(pUsuario.getContrasena());
    this.jtNombreComp.setText(pUsuario.getNombreCompleto());
    
    switch (pUsuario.getTipo()){
    
        case "Administrador":
            this.jcTipo.setSelectedIndex(0);
            break;
            
        case "Cajero":
            
           this.jcTipo.setSelectedIndex(1);
           break;
           
        case "Vendedor":
            
            this.jcTipo.setSelectedIndex(2);
            break;
            
    
    }
    }
    
    public boolean confirmarContrasena(){
    boolean correcta = false;
    
    if(this.jpContrasena.getText().equals(this.jpConfirmar.getText())){
    
    correcta =true;
    
      }
    return correcta;
    }

    public void mostrarMensaje (String pMensaje){
    
    JOptionPane.showMessageDialog(null, pMensaje);
    }
    
    public void agregarUsuarioTabla(String [] datos){
    
    this.modelo.addRow(datos);
    }
    
    
    public void modificarUsuarioTabla(String [] datos){
    
    for(int fila =0; fila< this.modelo.getRowCount(); fila++){
    
    if(this.modelo.getValueAt(fila, 0).equals(datos[0])){
    this.modelo.setValueAt(datos[1], fila, 1);
    this.modelo.setValueAt(datos[2], fila, 2);
    this.modelo.setValueAt(datos[3], fila, 3);
    break;
        }
      }
    }
    
    public void eliminarUsuarioTabla(String pUsuario){
    for(int fila=0; fila< this.modelo.getRowCount(); fila ++){
    if(this.modelo.getValueAt(fila, 0).equals(pUsuario)){
    this.modelo.removeRow(fila);
    break;
        }
      }
    }
    
    public String getUsuario(){
    return this.jtUsuario.getText();
    }
    
    public  void  recargarArchivo(){
        //se enviar la informacion del ArrayList<> al controlador de archivo
        this.controlador.archivo.setUsuarios(this.controlador.metodosUsuarios.usuarios);
        this.controlador.archivo.escribirInformacion();
        
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtNombreComp = new javax.swing.JTextField();
        jcTipo = new javax.swing.JComboBox<>();
        jP_Botones1 = new Vista.JP_Botones();
        jpContrasena = new javax.swing.JPasswordField();
        jpConfirmar = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaPerfiles = new javax.swing.JTable();

        setTitle("Formulario para perfiles de usuarios");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Usuario:");

        jtUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Contraseña:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Confirmar:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Nombre Completo:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tipo:");

        jtNombreComp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jcTipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Cajero", "Vendedor" }));

        jpContrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jpConfirmar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jpContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jpConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtNombreComp)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(140, 140, 140)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jP_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jpContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jtNombreComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jP_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jtListaPerfiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Usuario", "Contraseña", "NombreCompleto", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtListaPerfiles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    this.controlador.consolidarInformacion();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private Vista.JP_Botones jP_Botones1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcTipo;
    private javax.swing.JPasswordField jpConfirmar;
    private javax.swing.JPasswordField jpContrasena;
    private javax.swing.JTable jtListaPerfiles;
    private javax.swing.JTextField jtNombreComp;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
