/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.Controlador_FRM_BancoInformacion;
import Controlador.Controlador_FRM_Principal;

import javax.swing.JOptionPane;
import javax.swing.JTextField;


public class FRM_BancoInformacion extends javax.swing.JFrame {

   private  Controlador_FRM_BancoInformacion  controlador;
   
   //construtor recibe el controlar principal y lo envia al controlador de banco
    public FRM_BancoInformacion(Controlador_FRM_Principal pControladorPrincipal) {
        initComponents();
        
        //permite mostrar la interfaz en el centro
        this.setLocationRelativeTo(this);
        
        //se intancia el controlador
        this.controlador = new Controlador_FRM_BancoInformacion(this,pControladorPrincipal);
        
        //ponemos  a escuchar los  botones
        this.jbAplicar.addActionListener(controlador);
        this.jbCrear.addActionListener(controlador);
        this.jbSeleccionarBancoTrabajo.addActionListener(controlador);
        this.jbSeleccionarDireccionNuevoBanco.addActionListener(controlador);
        
    }
    
    public JTextField getJT_NombreBancoNuevo(){
        return  this.jtNombreBancoNuevo;
    }
    
    public JTextField  getJT_DireccionNuevoBanco(){
        return  this.jtDireccionBancoNuevo;
    }
    
    public void  mostrarMensaje(String pMensaje){
        JOptionPane.showMessageDialog(null,pMensaje);
    }
    
    public  void  estadoInicial(){
        this.jtDireccionBancoNuevo.setText("");
        this.jtNombreBancoNuevo.setText("");
    }
    
    public JTextField  getDireccionBancoTrabajar(){
        return  this.jtDireccionBancoTrabajo;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtDireccionBancoNuevo = new javax.swing.JTextField();
        jbCrear = new javax.swing.JButton();
        jtNombreBancoNuevo = new javax.swing.JTextField();
        jbSeleccionarDireccionNuevoBanco = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jbSeleccionarBancoTrabajo = new javax.swing.JButton();
        jtDireccionBancoTrabajo = new javax.swing.JTextField();
        jbAplicar = new javax.swing.JButton();

        setTitle("Banco de información");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Nombre del Banco Nuevo:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Crear Nuevo Banco información");

        jtDireccionBancoNuevo.setBackground(new java.awt.Color(255, 255, 204));
        jtDireccionBancoNuevo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtDireccionBancoNuevo.setEnabled(false);

        jbCrear.setBackground(new java.awt.Color(255, 153, 153));
        jbCrear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbCrear.setText("Crear");

        jtNombreBancoNuevo.setBackground(new java.awt.Color(255, 255, 204));
        jtNombreBancoNuevo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jbSeleccionarDireccionNuevoBanco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbSeleccionarDireccionNuevoBanco.setText("Seleccionar Dirección");
        jbSeleccionarDireccionNuevoBanco.setActionCommand("SeleccionarDireccion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtNombreBancoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbSeleccionarDireccionNuevoBanco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtDireccionBancoNuevo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbCrear)
                        .addGap(22, 22, 22)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(201, 201, 201))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNombreBancoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtDireccionBancoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSeleccionarDireccionNuevoBanco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCrear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Seleccionar Banco de información actual");

        jbSeleccionarBancoTrabajo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbSeleccionarBancoTrabajo.setText("Seleccionar Banco:");
        jbSeleccionarBancoTrabajo.setActionCommand("SeleccionarBanco");

        jtDireccionBancoTrabajo.setBackground(new java.awt.Color(255, 255, 204));
        jtDireccionBancoTrabajo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtDireccionBancoTrabajo.setEnabled(false);

        jbAplicar.setBackground(new java.awt.Color(255, 153, 153));
        jbAplicar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbAplicar.setText("Aplicar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jbSeleccionarBancoTrabajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtDireccionBancoTrabajo)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jbAplicar)
                        .addGap(33, 33, 33))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtDireccionBancoTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSeleccionarBancoTrabajo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAplicar)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbAplicar;
    private javax.swing.JButton jbCrear;
    private javax.swing.JButton jbSeleccionarBancoTrabajo;
    private javax.swing.JButton jbSeleccionarDireccionNuevoBanco;
    private javax.swing.JTextField jtDireccionBancoNuevo;
    private javax.swing.JTextField jtDireccionBancoTrabajo;
    private javax.swing.JTextField jtNombreBancoNuevo;
    // End of variables declaration//GEN-END:variables
}
