/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.Controlador_FRM_Principal;
import Vista.Frm_Login;
/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Frm_Principal extends javax.swing.JFrame {

    private Frm_Login frmLogin;
    private Controlador_FRM_Principal controlador;
    /**
     * Creates new form Frm_Principal
     */
    public Frm_Principal() {
        initComponents();
        
        
        this.controlador = new Controlador_FRM_Principal(this);
        
        this.jmiProductos.addActionListener(controlador);
        this.jmiClientes.addActionListener(controlador);
        this.jmi_CerrarSesion.addActionListener(controlador);
        this.jmiPerfiles.addActionListener(controlador);
        this.jmi_Facturacion.addActionListener(controlador);
        
        // se construye una instancia de interfaz login y recibe el contexto de principal
       
        
        this.jmiSalir.addActionListener(controlador);
        this.jmiProveedores.addActionListener(controlador);
        
        //se pone escuchar el  menu item banco de informacion
        this.jmiBancoInformacion.addActionListener(controlador);
        
    }
    
    public void CerrarSesion(){
        
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_CerrarSesion = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmiBancoInformacion = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();
        jmi_Usuarios = new javax.swing.JMenu();
        jmiProductos = new javax.swing.JMenuItem();
        jmiClientes = new javax.swing.JMenuItem();
        jmiPerfiles = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jmiProveedores = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmi_Facturacion = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Century", 0, 16)); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondo app.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/folder.png"))); // NOI18N
        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N

        jmi_CerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        jmi_CerrarSesion.setText("Cerrar Sesíon");
        jmi_CerrarSesion.setActionCommand("Cerrar Sesion");
        jMenu1.add(jmi_CerrarSesion);

        jMenuItem1.setText("Abrir");
        jMenu1.add(jMenuItem1);

        jmiBancoInformacion.setText("Banco de Información");
        jmiBancoInformacion.setActionCommand("BancoInformacion");
        jMenu1.add(jmiBancoInformacion);

        jmiSalir.setText("Salir");
        jMenu1.add(jmiSalir);

        jMenuBar1.add(jMenu1);

        jmi_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/notebook.png"))); // NOI18N
        jmi_Usuarios.setText("Catalogo");
        jmi_Usuarios.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N

        jmiProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jmiProductos.setText("Productos");
        jmi_Usuarios.add(jmiProductos);

        jmiClientes.setText("Clientes");
        jmi_Usuarios.add(jmiClientes);

        jmiPerfiles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jmiPerfiles.setText("Perfiles de Usuarios");
        jmiPerfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPerfilesActionPerformed(evt);
            }
        });
        jmi_Usuarios.add(jmiPerfiles);

        jMenu6.setText("Ventas");

        jMenuItem7.setText("jMenuItem7");
        jMenu6.add(jMenuItem7);

        jMenuItem8.setText("jMenuItem8");
        jMenu6.add(jMenuItem8);

        jmi_Usuarios.add(jMenu6);

        jMenuItem6.setText("Facturacion");
        jmi_Usuarios.add(jMenuItem6);

        jmiProveedores.setText("Proveedores");
        jmi_Usuarios.add(jmiProveedores);

        jMenuBar1.add(jmi_Usuarios);

        jMenu2.setText("Procesos");
        jMenu2.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N

        jmi_Facturacion.setText("Facturación");
        jmi_Facturacion.setActionCommand("Facturacion");
        jMenu2.add(jmi_Facturacion);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/search.png"))); // NOI18N
        jMenu3.setText("Consultas");
        jMenu3.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/settings (1).png"))); // NOI18N
        jMenu4.setText("Herramientas");
        jMenu4.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/view.png"))); // NOI18N
        jMenu5.setText("Ayuda");
        jMenu5.setFont(new java.awt.Font("Century", 0, 16)); // NOI18N
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiPerfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPerfilesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiPerfilesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Principal();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jmiBancoInformacion;
    private javax.swing.JMenuItem jmiClientes;
    private javax.swing.JMenuItem jmiPerfiles;
    private javax.swing.JMenuItem jmiProductos;
    private javax.swing.JMenuItem jmiProveedores;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuItem jmi_CerrarSesion;
    private javax.swing.JMenuItem jmi_Facturacion;
    private javax.swing.JMenu jmi_Usuarios;
    // End of variables declaration//GEN-END:variables
}
