/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_productos;
import Controlador.Controlador_FRM_clientes;
import Controlador.Controlador_FRM_proveedores;
import Controlador.Controlador_FRM_Usuarios;
/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class JP_Botones extends javax.swing.JPanel {

    /**
     * Creates new form JP_Botones
     */
    public JP_Botones() {
        initComponents();
        
    }
    
    
    public void estadoInicialBotones(){
    this.BtnConsultar.setEnabled(true);
    this.BtnIngresar.setEnabled(false);
    this.btnModificar.setEnabled(false);
    this.BtnEliminar.setEnabled(false);
    this.btnLimpiar.setEnabled(true);
    
}
    
    
    /***metodo encargado de asignar el controlador de la botonera***/
public void agregarControladorP (Controlador_FRM_productos controlador){
    this.BtnConsultar.addActionListener(controlador);
    this.btnModificar.addActionListener(controlador);
    this.BtnIngresar.addActionListener(controlador);
    this.BtnEliminar.addActionListener(controlador);
    this.btnLimpiar.addActionListener(controlador);
    
    
}

public void agregarControladorC (Controlador_FRM_clientes controlador){
    this.BtnConsultar.addActionListener(controlador);
    this.btnModificar.addActionListener(controlador);
    this.BtnIngresar.addActionListener(controlador);
    this.BtnEliminar.addActionListener(controlador);
    this.btnLimpiar.addActionListener(controlador);
    
    
}

public void agregarControladorU (Controlador_FRM_Usuarios controlador){
    this.BtnConsultar.addActionListener(controlador);
    this.btnModificar.addActionListener(controlador);
    this.BtnIngresar.addActionListener(controlador);
    this.BtnEliminar.addActionListener(controlador);
    this.btnLimpiar.addActionListener(controlador);
}


public void agregarControladorProve(Controlador_FRM_proveedores controlador){
    this.BtnConsultar.addActionListener(controlador);
    this.btnModificar.addActionListener(controlador);
    this.BtnIngresar.addActionListener(controlador);
    this.BtnEliminar.addActionListener(controlador);
    this.btnLimpiar.addActionListener(controlador);
    
}


public void habilitarBotoneraAgregar(){
this.BtnConsultar.setEnabled(false);
this.btnModificar.setEnabled(false);
this.BtnIngresar.setEnabled(true);
this.BtnEliminar.setEnabled(false);
this.btnLimpiar.setEnabled(true);


}

public void habilitarBotoneraModificarEliminar(){
    
this.BtnConsultar.setEnabled(false);
this.btnModificar.setEnabled(true);
this.BtnIngresar.setEnabled(false);
this.BtnEliminar.setEnabled(true);
this.btnLimpiar.setEnabled(true);
    
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnConsultar = new javax.swing.JButton();
        BtnIngresar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        BtnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Consultar.png"))); // NOI18N
        BtnConsultar.setToolTipText("Consultar");
        BtnConsultar.setActionCommand("Buscar");

        BtnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Registrar.png"))); // NOI18N
        BtnIngresar.setToolTipText("Ingresar");
        BtnIngresar.setActionCommand("Registrar");
        BtnIngresar.setEnabled(false);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Modificar.png"))); // NOI18N
        btnModificar.setToolTipText("Modificar");
        btnModificar.setActionCommand("Modificar");
        btnModificar.setEnabled(false);

        BtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Eliminar.png"))); // NOI18N
        BtnEliminar.setToolTipText("Eliminar");
        BtnEliminar.setActionCommand("Eliminar");
        BtnEliminar.setEnabled(false);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/29571273_1912350045464465_7969678650884751360_n.png"))); // NOI18N
        btnLimpiar.setActionCommand("Limpiar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(BtnConsultar)
                .addGap(27, 27, 27)
                .addComponent(BtnIngresar)
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(BtnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLimpiar)
                    .addComponent(BtnConsultar)
                    .addComponent(BtnIngresar)
                    .addComponent(btnModificar)
                    .addComponent(BtnEliminar))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConsultar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
