/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import controlador.Controlador_FRM_productos;
import controlador.Controlador_Frm_Usuarios;
import controlador.Controlador_FRM_Clientes;
import controlador.Controlador_FRM_Provedores;
/**
 *
 * @author Melber
 */
public class JP_Botones extends javax.swing.JPanel {

    /**
     * Creates new form JP_Botones
     */
    public JP_Botones() {
        initComponents();
    }

    public void agregarControladorProductos(Controlador_FRM_productos  controlador){
        
        this.btnConsultar.addActionListener(controlador);
        this.btnRegistrar.addActionListener(controlador);
        this.btnModificar.addActionListener(controlador);
        this.btnEliminar.addActionListener(controlador);
        this.btnLimpiar.addActionListener(controlador);
    }
    public void agregarControladorClientes(Controlador_FRM_Clientes  controlador){
        
        this.btnConsultar.addActionListener(controlador);
        this.btnRegistrar.addActionListener(controlador);
        this.btnModificar.addActionListener(controlador);
        this.btnEliminar.addActionListener(controlador);
        this.btnLimpiar.addActionListener(controlador);
    }
    public void agregarControladorProveedores(Controlador_FRM_Provedores  controlador){
        
        this.btnConsultar.addActionListener(controlador);
        this.btnRegistrar.addActionListener(controlador);
        this.btnModificar.addActionListener(controlador);
        this.btnEliminar.addActionListener(controlador);
        this.btnLimpiar.addActionListener(controlador);
    }
    
    public void agregarControladorUsuarios(Controlador_Frm_Usuarios controlador) {
        
        this.btnConsultar.addActionListener(controlador);
        this.btnRegistrar.addActionListener(controlador);
        this.btnModificar.addActionListener(controlador);
        this.btnEliminar.addActionListener(controlador);
        this.btnLimpiar.addActionListener(controlador);
        
    }
    
    public void estadoInicialBotones(){
        this.btnConsultar.setEnabled(true);
        this.btnRegistrar.setEnabled(false);
        this.btnModificar.setEnabled(false);
        this.btnEliminar.setEnabled(false);
    }
    public void habilitarAgregar(){
        
        this.btnConsultar.setEnabled(false);
        this.btnRegistrar.setEnabled(true);
        this.btnModificar.setEnabled(false);
        this.btnEliminar.setEnabled(false);
    }
    public void habilitarModificarEliminar(){
        this.btnConsultar.setEnabled(false);
        this.btnRegistrar.setEnabled(false);
        this.btnModificar.setEnabled(true);
        this.btnEliminar.setEnabled(true);
                
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConsultar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(32767, 32000));

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Consultar.png"))); // NOI18N
        btnConsultar.setToolTipText("Consultar");
        btnConsultar.setActionCommand("Buscar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Registrar.png"))); // NOI18N
        btnRegistrar.setToolTipText("Registrar");
        btnRegistrar.setActionCommand("Registrar");
        btnRegistrar.setEnabled(false);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Modificar.png"))); // NOI18N
        btnModificar.setToolTipText("Modificar");
        btnModificar.setActionCommand("Modificar");
        btnModificar.setEnabled(false);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Eliminar.png"))); // NOI18N
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.setActionCommand("Eliminar");
        btnEliminar.setEnabled(false);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/limpiar.png"))); // NOI18N
        btnLimpiar.setToolTipText("Limpiar");
        btnLimpiar.setActionCommand("Limpiar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnConsultar)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addGap(32, 32, 32)
                .addComponent(btnModificar)
                .addGap(31, 31, 31)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnLimpiar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLimpiar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultar)
                            .addComponent(btnRegistrar)
                            .addComponent(btnModificar))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    // End of variables declaration//GEN-END:variables
}
